package study.android.kotlindbnotes

object TestData {
       val russianCompanies2020 = listOf(
            ResultEntity(0, "En+ Group", 6693),
            ResultEntity(0, "Etalon Group", 510),
            ResultEntity(0, "Global Ports", 573),
            ResultEntity(0, "Globaltrans", 1068),
            ResultEntity(0, "HeadHunter", 1513),
            ResultEntity(0, "Mail.Ru Group", 5928),
            ResultEntity(0, "QIWI", 646),
            ResultEntity(0, "VEON (VimpelCom)", 2641),
            ResultEntity(0, "X5 Retail Group", 9809),
            ResultEntity(0, "Акрон", 3272),
            ResultEntity(0, "АЛРОСА", 9855),
            ResultEntity(0, "АЛРОСА-Нюрба", 641),
            ResultEntity(0, "Аптечная сеть 36,6", 1438),
            ResultEntity(0, "АФК «Система»", 3772),
            ResultEntity(0, "Аэрофлот", 2363),
            ResultEntity(0, "Банк «Санкт-Петербург»", 341),
            ResultEntity(0, "Банк Авангард", 1147),
            ResultEntity(0, "Банк ВТБ", 6639),
            ResultEntity(0, "БАНК УРАЛСИБ", 332),
            ResultEntity(0, "Башнефть", 3322),
            ResultEntity(0, "ВСМПО-АВИСМА", 3296),
            ResultEntity(0, "Газпром", 68012),
            ResultEntity(0, "Газпром нефть", 20406),
            ResultEntity(0, "ГК «Мать и дитя»", 458),
            ResultEntity(0, "Группа «Самолет»", 795),
            ResultEntity(0, "Группа «Черкизово»", 1094),
            ResultEntity(0, "Группа Компаний ПИК", 5338),
            ResultEntity(0, "Группа ЛСР", 1211),
            ResultEntity(0, "ДВМП", 460),
            ResultEntity(0, "Детский мир", 1362),
            ResultEntity(0, "ЕВРАЗ", 9394),
            ResultEntity(0, "ИНГРАД", 659),
            ResultEntity(0, "Интер РАО", 7514),
            ResultEntity(0, "Иркутскэнерго", 750),
            ResultEntity(0, "Казаньоргсин­тез", 1957),
            ResultEntity(0, "КАМАЗ", 618),
            ResultEntity(0, "Корпорация «Иркут»", 700),
            ResultEntity(0, "Кубаньэнерго", 307),
            ResultEntity(0, "КуйбышевАзот", 493),
            ResultEntity(0, "Лента", 1635),
            ResultEntity(0, "ЛУКОЙЛ", 48601),
            ResultEntity(0, "М.Видео", 1733),
            ResultEntity(0, "Магнит", 7828),
            ResultEntity(0, "МГТС", 2368),
            ResultEntity(0, "Мечел", 442),
            ResultEntity(0, "ММК", 8477),
            ResultEntity(0, "Московская Биржа", 4914),
            ResultEntity(0, "МОСКОВСКИЙ КРЕДИТНЫЙ БАНК", 2482),
            ResultEntity(0, "МОСТОТРЕСТ", 401),
            ResultEntity(0, "Мосэнерго", 1115),
            ResultEntity(0, "МРСК Центра и Приволжья", 385),
            ResultEntity(0, "МТС", 8916),
            ResultEntity(0, "Нижнекамск­нефтехим", 1979),
            ResultEntity(0, "НК «Роснефть»", 62534),
            ResultEntity(0, "НК «РуссНефть»", 936),
            ResultEntity(0, "НКХП", 305),
            ResultEntity(0, "НЛМК", 16941),
            ResultEntity(0, "НМТП", 2108),
            ResultEntity(0, "НОВАТЭК", 51630),
            ResultEntity(0, "Норильский никель", 50604),
            ResultEntity(0, "ОАК", 2647),
            ResultEntity(0, "Объединенные Кредитные Системы", 446),
            ResultEntity(0, "ОГК-2", 1096),
            ResultEntity(0, "ОЗОН", 8622),
            ResultEntity(0, "Петропавловск ", 1666),
            ResultEntity(0, "Полиметалл", 11142),
            ResultEntity(0, "Полюс", 27738),
            ResultEntity(0, "Распадская", 1446),
            ResultEntity(0, "РОСБАНК", 1621),
            ResultEntity(0, "Росгосстрах", 2038),
            ResultEntity(0, "Россети", 4761),
            ResultEntity(0, "Россети Ленэнерго", 603),
            ResultEntity(0, "Россети Московский регион (МОЭСК)", 921),
            ResultEntity(0, "Россети Северный Кавказ (МРСК Северного Кавказа)", 354),
            ResultEntity(0, "Россети Сибирь (МРСК Сибири)", 492),
            ResultEntity(0, "Ростелеком", 4299),
            ResultEntity(0, "Русагро", 1493),
            ResultEntity(0, "РУСАЛ", 7263),
            ResultEntity(0, "РусГидро", 4680),
            ResultEntity(0, "Русолово", 320),
            ResultEntity(0, "Русская Аквакультура", 310),
            ResultEntity(0, "САФМАР Финансовые инвестиции", 746),
            ResultEntity(0, "Сбербанк", 79504),
            ResultEntity(0, "Северсталь", 15029),
            ResultEntity(0, "Селигдар", 520),
            ResultEntity(0, "Славнефть-Мегионнефте­газ", 421),
            ResultEntity(0, "Совкомфлот", 2917),
            ResultEntity(0, "Сургутнефтегаз", 17405),
            ResultEntity(0, "Татнефть", 15176),
            ResultEntity(0, "ТГК-1", 580),
            ResultEntity(0, "Тинькофф Банк", 6557),
            ResultEntity(0, "ТМК", 860),
            ResultEntity(0, "ФосАгро", 5534),
            ResultEntity(0, "ФСК ЕЭС", 3835),
            ResultEntity(0, "ЧТПЗ", 1049),
            ResultEntity(0, "Энел Россия", 432),
            ResultEntity(0, "Юнипро", 2387),
            ResultEntity(0, "ЮТэйр", 332),
            ResultEntity(0, "Яндекс", 22122),
            ResultEntity(0, "ЯТЭК", 597),

            )
}
